/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OpsRouteImport } from './routes/_ops'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as OpsIndexRouteImport } from './routes/_ops/index'
import { Route as OpsAccountsRouteImport } from './routes/_ops/accounts'
import { Route as OpsDeepRefsRouteImport } from './routes/_ops/deep-refs'
import { Route as OpsDownloadsRouteImport } from './routes/_ops/downloads'
import { Route as OpsPluginsRouteImport } from './routes/_ops/plugins'
import { Route as OpsPoolRouteImport } from './routes/_ops/pool'
import { Route as OpsScrapeRouteImport } from './routes/_ops/scrape'
import { Route as ApiInngestRouteImport } from './routes/api.inngest'
import { Route as ApiIptvCatalogScrapeRouteImport } from './routes/api.iptv-catalog-scrape'
import { Route as ApiIptvCatalogVerifyRouteImport } from './routes/api.iptv-catalog-verify'
import { Route as ApiIptvDeepRefReprocessRouteImport } from './routes/api.iptv-deep-ref-reprocess'
import { Route as ApiIptvPasteBodyRouteImport } from './routes/api.iptv-paste-body'
import { Route as ApiIptvPromoteBackfillRouteImport } from './routes/api.iptv-promote-backfill'
import { Route as ApiIptvStalkerNoteBackfillRouteImport } from './routes/api.iptv-stalker-note-backfill'
import { Route as ApiPluginPackFetchRouteImport } from './routes/api.plugin-pack-fetch'
import { Route as ApiPosthogPersonsRouteImport } from './routes/api.posthog-persons'
import { Route as ApiR2DownloadStatsRouteImport } from './routes/api.r2-download-stats'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginMfaRouteImport } from './routes/_auth/login.mfa'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/_ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAccountsRoute = OpsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDeepRefsRoute = OpsDeepRefsRouteImport.update({
  id: '/deep-refs',
  path: '/deep-refs',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDownloadsRoute = OpsDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPluginsRoute = OpsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPoolRoute = OpsPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => OpsRoute,
} as any)
const OpsScrapeRoute = OpsScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => OpsRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvCatalogScrapeRoute = ApiIptvCatalogScrapeRouteImport.update({
  id: '/api/iptv-catalog-scrape',
  path: '/api/iptv-catalog-scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvCatalogVerifyRoute = ApiIptvCatalogVerifyRouteImport.update({
  id: '/api/iptv-catalog-verify',
  path: '/api/iptv-catalog-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvDeepRefReprocessRoute = ApiIptvDeepRefReprocessRouteImport.update({
  id: '/api/iptv-deep-ref-reprocess',
  path: '/api/iptv-deep-ref-reprocess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvPasteBodyRoute = ApiIptvPasteBodyRouteImport.update({
  id: '/api/iptv-paste-body',
  path: '/api/iptv-paste-body',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvPromoteBackfillRoute = ApiIptvPromoteBackfillRouteImport.update({
  id: '/api/iptv-promote-backfill',
  path: '/api/iptv-promote-backfill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvStalkerNoteBackfillRoute =
  ApiIptvStalkerNoteBackfillRouteImport.update({
    id: '/api/iptv-stalker-note-backfill',
    path: '/api/iptv-stalker-note-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPluginPackFetchRoute = ApiPluginPackFetchRouteImport.update({
  id: '/api/plugin-pack-fetch',
  path: '/api/plugin-pack-fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosthogPersonsRoute = ApiPosthogPersonsRouteImport.update({
  id: '/api/posthog-persons',
  path: '/api/posthog-persons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2DownloadStatsRoute = ApiR2DownloadStatsRouteImport.update({
  id: '/api/r2-download-stats',
  path: '/api/r2-download-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginMfaRoute = AuthLoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OpsIndexRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/accounts': typeof OpsAccountsRoute
  '/deep-refs': typeof OpsDeepRefsRoute
  '/downloads': typeof OpsDownloadsRoute
  '/plugins': typeof OpsPluginsRoute
  '/pool': typeof OpsPoolRoute
  '/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-catalog-scrape': typeof ApiIptvCatalogScrapeRoute
  '/api/iptv-catalog-verify': typeof ApiIptvCatalogVerifyRoute
  '/api/iptv-deep-ref-reprocess': typeof ApiIptvDeepRefReprocessRoute
  '/api/iptv-paste-body': typeof ApiIptvPasteBodyRoute
  '/api/iptv-promote-backfill': typeof ApiIptvPromoteBackfillRoute
  '/api/iptv-stalker-note-backfill': typeof ApiIptvStalkerNoteBackfillRoute
  '/api/plugin-pack-fetch': typeof ApiPluginPackFetchRoute
  '/api/posthog-persons': typeof ApiPosthogPersonsRoute
  '/api/r2-download-stats': typeof ApiR2DownloadStatsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/mfa': typeof AuthLoginMfaRoute
}
export interface FileRoutesByTo {
  '/': typeof OpsIndexRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/accounts': typeof OpsAccountsRoute
  '/deep-refs': typeof OpsDeepRefsRoute
  '/downloads': typeof OpsDownloadsRoute
  '/plugins': typeof OpsPluginsRoute
  '/pool': typeof OpsPoolRoute
  '/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-catalog-scrape': typeof ApiIptvCatalogScrapeRoute
  '/api/iptv-catalog-verify': typeof ApiIptvCatalogVerifyRoute
  '/api/iptv-deep-ref-reprocess': typeof ApiIptvDeepRefReprocessRoute
  '/api/iptv-paste-body': typeof ApiIptvPasteBodyRoute
  '/api/iptv-promote-backfill': typeof ApiIptvPromoteBackfillRoute
  '/api/iptv-stalker-note-backfill': typeof ApiIptvStalkerNoteBackfillRoute
  '/api/plugin-pack-fetch': typeof ApiPluginPackFetchRoute
  '/api/posthog-persons': typeof ApiPosthogPersonsRoute
  '/api/r2-download-stats': typeof ApiR2DownloadStatsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/mfa': typeof AuthLoginMfaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_ops': typeof OpsRouteWithChildren
  '/_auth/login': typeof AuthLoginRouteWithChildren
  '/_ops/accounts': typeof OpsAccountsRoute
  '/_ops/deep-refs': typeof OpsDeepRefsRoute
  '/_ops/downloads': typeof OpsDownloadsRoute
  '/_ops/plugins': typeof OpsPluginsRoute
  '/_ops/pool': typeof OpsPoolRoute
  '/_ops/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-catalog-scrape': typeof ApiIptvCatalogScrapeRoute
  '/api/iptv-catalog-verify': typeof ApiIptvCatalogVerifyRoute
  '/api/iptv-deep-ref-reprocess': typeof ApiIptvDeepRefReprocessRoute
  '/api/iptv-paste-body': typeof ApiIptvPasteBodyRoute
  '/api/iptv-promote-backfill': typeof ApiIptvPromoteBackfillRoute
  '/api/iptv-stalker-note-backfill': typeof ApiIptvStalkerNoteBackfillRoute
  '/api/plugin-pack-fetch': typeof ApiPluginPackFetchRoute
  '/api/posthog-persons': typeof ApiPosthogPersonsRoute
  '/api/r2-download-stats': typeof ApiR2DownloadStatsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_ops/': typeof OpsIndexRoute
  '/_auth/login/mfa': typeof AuthLoginMfaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/deep-refs'
    | '/downloads'
    | '/plugins'
    | '/pool'
    | '/scrape'
    | '/api/inngest'
    | '/api/iptv-catalog-scrape'
    | '/api/iptv-catalog-verify'
    | '/api/iptv-deep-ref-reprocess'
    | '/api/iptv-paste-body'
    | '/api/iptv-promote-backfill'
    | '/api/iptv-stalker-note-backfill'
    | '/api/plugin-pack-fetch'
    | '/api/posthog-persons'
    | '/api/r2-download-stats'
    | '/auth/callback'
    | '/login/mfa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/deep-refs'
    | '/downloads'
    | '/plugins'
    | '/pool'
    | '/scrape'
    | '/api/inngest'
    | '/api/iptv-catalog-scrape'
    | '/api/iptv-catalog-verify'
    | '/api/iptv-deep-ref-reprocess'
    | '/api/iptv-paste-body'
    | '/api/iptv-promote-backfill'
    | '/api/iptv-stalker-note-backfill'
    | '/api/plugin-pack-fetch'
    | '/api/posthog-persons'
    | '/api/r2-download-stats'
    | '/auth/callback'
    | '/login/mfa'
  id:
    | '__root__'
    | '/_auth'
    | '/_ops'
    | '/_auth/login'
    | '/_ops/accounts'
    | '/_ops/deep-refs'
    | '/_ops/downloads'
    | '/_ops/plugins'
    | '/_ops/pool'
    | '/_ops/scrape'
    | '/api/inngest'
    | '/api/iptv-catalog-scrape'
    | '/api/iptv-catalog-verify'
    | '/api/iptv-deep-ref-reprocess'
    | '/api/iptv-paste-body'
    | '/api/iptv-promote-backfill'
    | '/api/iptv-stalker-note-backfill'
    | '/api/plugin-pack-fetch'
    | '/api/posthog-persons'
    | '/api/r2-download-stats'
    | '/auth/callback'
    | '/_ops/'
    | '/_auth/login/mfa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiIptvCatalogScrapeRoute: typeof ApiIptvCatalogScrapeRoute
  ApiIptvCatalogVerifyRoute: typeof ApiIptvCatalogVerifyRoute
  ApiIptvDeepRefReprocessRoute: typeof ApiIptvDeepRefReprocessRoute
  ApiIptvPasteBodyRoute: typeof ApiIptvPasteBodyRoute
  ApiIptvPromoteBackfillRoute: typeof ApiIptvPromoteBackfillRoute
  ApiIptvStalkerNoteBackfillRoute: typeof ApiIptvStalkerNoteBackfillRoute
  ApiPluginPackFetchRoute: typeof ApiPluginPackFetchRoute
  ApiPosthogPersonsRoute: typeof ApiPosthogPersonsRoute
  ApiR2DownloadStatsRoute: typeof ApiR2DownloadStatsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops': {
      id: '/_ops'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_ops/': {
      id: '/_ops/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/accounts': {
      id: '/_ops/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof OpsAccountsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/deep-refs': {
      id: '/_ops/deep-refs'
      path: '/deep-refs'
      fullPath: '/deep-refs'
      preLoaderRoute: typeof OpsDeepRefsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/downloads': {
      id: '/_ops/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof OpsDownloadsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/plugins': {
      id: '/_ops/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof OpsPluginsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/pool': {
      id: '/_ops/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof OpsPoolRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/scrape': {
      id: '/_ops/scrape'
      path: '/scrape'
      fullPath: '/scrape'
      preLoaderRoute: typeof OpsScrapeRouteImport
      parentRoute: typeof OpsRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-catalog-scrape': {
      id: '/api/iptv-catalog-scrape'
      path: '/api/iptv-catalog-scrape'
      fullPath: '/api/iptv-catalog-scrape'
      preLoaderRoute: typeof ApiIptvCatalogScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-catalog-verify': {
      id: '/api/iptv-catalog-verify'
      path: '/api/iptv-catalog-verify'
      fullPath: '/api/iptv-catalog-verify'
      preLoaderRoute: typeof ApiIptvCatalogVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-deep-ref-reprocess': {
      id: '/api/iptv-deep-ref-reprocess'
      path: '/api/iptv-deep-ref-reprocess'
      fullPath: '/api/iptv-deep-ref-reprocess'
      preLoaderRoute: typeof ApiIptvDeepRefReprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-paste-body': {
      id: '/api/iptv-paste-body'
      path: '/api/iptv-paste-body'
      fullPath: '/api/iptv-paste-body'
      preLoaderRoute: typeof ApiIptvPasteBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-promote-backfill': {
      id: '/api/iptv-promote-backfill'
      path: '/api/iptv-promote-backfill'
      fullPath: '/api/iptv-promote-backfill'
      preLoaderRoute: typeof ApiIptvPromoteBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-stalker-note-backfill': {
      id: '/api/iptv-stalker-note-backfill'
      path: '/api/iptv-stalker-note-backfill'
      fullPath: '/api/iptv-stalker-note-backfill'
      preLoaderRoute: typeof ApiIptvStalkerNoteBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugin-pack-fetch': {
      id: '/api/plugin-pack-fetch'
      path: '/api/plugin-pack-fetch'
      fullPath: '/api/plugin-pack-fetch'
      preLoaderRoute: typeof ApiPluginPackFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posthog-persons': {
      id: '/api/posthog-persons'
      path: '/api/posthog-persons'
      fullPath: '/api/posthog-persons'
      preLoaderRoute: typeof ApiPosthogPersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-download-stats': {
      id: '/api/r2-download-stats'
      path: '/api/r2-download-stats'
      fullPath: '/api/r2-download-stats'
      preLoaderRoute: typeof ApiR2DownloadStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/mfa': {
      id: '/_auth/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof AuthLoginMfaRouteImport
      parentRoute: typeof AuthLoginRoute
    }
  }
}

interface AuthLoginRouteChildren {
  AuthLoginMfaRoute: typeof AuthLoginMfaRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLoginMfaRoute: AuthLoginMfaRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OpsRouteChildren {
  OpsAccountsRoute: typeof OpsAccountsRoute
  OpsDeepRefsRoute: typeof OpsDeepRefsRoute
  OpsDownloadsRoute: typeof OpsDownloadsRoute
  OpsPluginsRoute: typeof OpsPluginsRoute
  OpsPoolRoute: typeof OpsPoolRoute
  OpsScrapeRoute: typeof OpsScrapeRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAccountsRoute: OpsAccountsRoute,
  OpsDeepRefsRoute: OpsDeepRefsRoute,
  OpsDownloadsRoute: OpsDownloadsRoute,
  OpsPluginsRoute: OpsPluginsRoute,
  OpsPoolRoute: OpsPoolRoute,
  OpsScrapeRoute: OpsScrapeRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiIptvCatalogScrapeRoute: ApiIptvCatalogScrapeRoute,
  ApiIptvCatalogVerifyRoute: ApiIptvCatalogVerifyRoute,
  ApiIptvDeepRefReprocessRoute: ApiIptvDeepRefReprocessRoute,
  ApiIptvPasteBodyRoute: ApiIptvPasteBodyRoute,
  ApiIptvPromoteBackfillRoute: ApiIptvPromoteBackfillRoute,
  ApiIptvStalkerNoteBackfillRoute: ApiIptvStalkerNoteBackfillRoute,
  ApiPluginPackFetchRoute: ApiPluginPackFetchRoute,
  ApiPosthogPersonsRoute: ApiPosthogPersonsRoute,
  ApiR2DownloadStatsRoute: ApiR2DownloadStatsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
